// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfudrphnavcercdkuoub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdWRycGhuYXZjZXJjZGt1b3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MjcyOTksImV4cCI6MjA1MzUwMzI5OX0.YE_dyS4FyIOOTc-TmHkvPH86gDnfaE8KSgueX8YnN2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);